name: Job Agent Runner

on:
  schedule:
    - cron: "0 9 */3 * *"  # every 3 days at 9AM UTC
  workflow_dispatch:       # allows manual run button

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run job agent
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        run: python job_agent.py
